kc_q = KbName('q');	  % Quit
kc_x = KbName('x');	  % Toggle Bullseye 
kv_z = KbName('z'); 	% Back BlackScreen
kv_m = KbName('m'); 	% Grey Screen
kv_w = KbName('w');   % White Screen
kv_r = KbName('r');   % Red Screen
kv_g = KbName('g');   % Green Screen
kv_b = KbName('b');   % Blue Screen
kv_1 = KbName('1');   % Test Stimulus 1: Fullfield flash
kv_2 = KbName('2');   % Test Stimulus 2: Drift Grating 10 deg 1 Hz
kv_3 = KbName('3');   % Test Stimulus 3: RF Search
kv_4 = KbName('4');   % Test Stimulus 4: 
kv_5 = KbName('5');   % Test Stimulus 5: 
kv_6 = KbName('6');   % Test Stimulus 6: 
kv_7 = KbName('7');   % Test Stimulus 7: 
kv_9 = KbName('8');   % Test Stimulus 8: 
kv_9 = KbName('9');   % Test Stimulus 9: 
kv_0 = KbName('0');   % Test Stimulus 0:  